on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  NODE_VERSION: '16.x' # set this to the node version to use

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Heroku
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install package
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_API_KEY }}
          procfile: 'web: yarn start:prod'
        env:
          HD_PORT: ${{ secrets.PORT }}
          HD_MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          HD_MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          HD_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          HD_MONGO_URL: ${{ secrets.MONGO_URL }}
