on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  NODE_VERSION: '16.x' # set this to the node version to use

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Heroku
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install package
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_API_KEY }}
          procfile: 'web: yarn start:prod'
        env:
          HD_PORT: ${{ secrets.PORT }}
          HD_MONGO_URL: ${{ secrets.MONGO_URL }}
          HD_MONGO_STORAGE_URL: ${{ secrets.MONGO_STORAGE_URL }}
          HD_ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
          HD_ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}
          HD_REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
          HD_REFRESH_TOKEN_EXPIRE: ${{ secrets.REFRESH_TOKEN_EXPIRE }}